title: Thibault Sellam
email: thibault.sellam@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Thibault Sellam's homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sellam.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tsellam
navigation_footer:

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Email: mailto:thibault.sellam@gmail.com
  GitHub: https://github.com/tsellam
  LinkedIn: https://www.linkedin.com/in/thibault-sellam-443198a/

sass:
  style: compressed # Style compression

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
# remote_theme: daviddarnes/alembic
#theme: alembic-jekyll-theme

# 8. Site navigation
# Home: /
# Publications: /publications/
# Projects: /projects/
# Blog: /blog/
# Other: /other/
navigation_header:
- title: Home
  url: /
- title: Publications
  url: /publications/
- title: Blog
  url: /blog/

navigation_footer:
  Thibault Sellam

exclude:
  - .jekyll-cache

remote_theme: daviddarnes/alembic@main
